//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautyMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautyMXEntities : DbContext
    {
        public BeautyMXEntities()
            : base("name=BeautyMXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bottle> Bottles { get; set; }
        public virtual DbSet<BottleRequest> BottleRequests { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }

        public System.Data.Entity.DbSet<BeautyMX.Models._BottleRequest> _BottleRequest { get; set; }

        public System.Data.Entity.DbSet<BeautyMX.Models._Vendor> _Vendor { get; set; }
    }
}
